# Generated by Django 3.2.5 on 2022-02-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('isbn', models.PositiveIntegerField()),
                ('edition', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('pages', models.PositiveSmallIntegerField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
